"""add spotify_id and spotify_artist_id to reviews and catalog_items tables

Revision ID: 09aef735abb2
Revises: 0a2797dd3110
Create Date: 2025-01-23 14:46:47.515687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09aef735abb2'
down_revision = '0a2797dd3110'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalog_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spotify_id', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('spotify_artist_id', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('private', sa.Boolean(), nullable=False))
        batch_op.create_unique_constraint(None, ['spotify_id'])
        batch_op.create_unique_constraint(None, ['spotify_artist_id'])

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spotify_id', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('spotify_artist_id', sa.String(length=128), nullable=True))
        batch_op.create_unique_constraint(None, ['spotify_id'])
        batch_op.create_unique_constraint(None, ['spotify_artist_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('spotify_artist_id')
        batch_op.drop_column('spotify_id')

    with op.batch_alter_table('catalog_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('private')
        batch_op.drop_column('spotify_artist_id')
        batch_op.drop_column('spotify_id')

    # ### end Alembic commands ###
