"""add music_item_type_enum

Revision ID: 0a2797dd3110
Revises: e2a4ab2e45e7
Create Date: 2025-01-21 20:04:08.159452

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision = '0a2797dd3110'
down_revision = 'e2a4ab2e45e7'
branch_labels = None
depends_on = None


music_item_type_enum = ENUM('artist', 'album', 'track', name='music_item_type_enum', create_type=False)


def upgrade():
    music_item_type_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalog_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_type', sa.Enum('ALBUM', 'ARTIST', 'TRACK', name='music_item_type_enum'), nullable=False))

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_type', sa.Enum('ALBUM', 'ARTIST', 'TRACK', name='music_item_type_enum'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('item_type')

    with op.batch_alter_table('catalog_items', schema=None) as batch_op:
        batch_op.drop_column('item_type')

    # ### end Alembic commands ###

    music_item_type_enum.drop(op.get_bind(), checkfirst=True)
