"""remove unused columns from reviews table

Revision ID: 24276f3241f8
Revises: fbab0c91ebfc
Create Date: 2025-01-28 16:03:40.673119

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '24276f3241f8'
down_revision = 'fbab0c91ebfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('spotify_id',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.alter_column('spotify_artist_id',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.drop_constraint('reviews_track_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('reviews_album_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('reviews_artist_id_fkey', type_='foreignkey')
        batch_op.drop_column('item_type')
        batch_op.drop_column('track_id')
        batch_op.drop_column('artist_id')
        batch_op.drop_column('album_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('album_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('track_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('item_type', postgresql.ENUM('artist', 'album', 'track', name='music_item_type_enum'), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('reviews_artist_id_fkey', 'artists', ['artist_id'], ['id'])
        batch_op.create_foreign_key('reviews_album_id_fkey', 'albums', ['album_id'], ['id'])
        batch_op.create_foreign_key('reviews_track_id_fkey', 'tracks', ['track_id'], ['id'])
        batch_op.alter_column('spotify_artist_id',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('spotify_id',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)

    # ### end Alembic commands ###
