"""add indices to spotify_id columns

Revision ID: 3c0aca4bef07
Revises: 24276f3241f8
Create Date: 2025-01-28 16:31:04.188671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c0aca4bef07'
down_revision = '24276f3241f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.drop_constraint('albums_spotify_id_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_albums_spotify_id'), ['spotify_id'], unique=True)

    with op.batch_alter_table('artist_album_track', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spotify_id', sa.String(length=128), nullable=True))
        batch_op.alter_column('album_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_artist_album_track_spotify_id'), ['spotify_id'], unique=True)

    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.drop_constraint('artists_spotify_id_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_artists_spotify_id'), ['spotify_id'], unique=True)

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'artists', ['spotify_artist_id'], ['spotify_id'])

    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_constraint('tracks_spotify_id_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_tracks_spotify_id'), ['spotify_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tracks_spotify_id'))
        batch_op.create_unique_constraint('tracks_spotify_id_key', ['spotify_id'])

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('rating',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artists_spotify_id'))
        batch_op.create_unique_constraint('artists_spotify_id_key', ['spotify_id'])

    with op.batch_alter_table('artist_album_track', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artist_album_track_spotify_id'))
        batch_op.alter_column('album_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('spotify_id')

    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_albums_spotify_id'))
        batch_op.create_unique_constraint('albums_spotify_id_key', ['spotify_id'])

    # ### end Alembic commands ###
