"""private was running into reserved keyword issues on the frontend, what are the odds it doesn't come up eventually in the backend too?

Revision ID: 45530d49033d
Revises: 3c0aca4bef07
Create Date: 2025-01-28 19:37:59.320618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45530d49033d'
down_revision = '3c0aca4bef07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_private', sa.Boolean(), nullable=False))
        batch_op.drop_column('private')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('private', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('is_private')

    # ### end Alembic commands ###
