"""Add tables, columns, and relationships for albums, tracks, and artists

Revision ID: 7c94b0590246
Revises: 7e12f25f42a3
Create Date: 2024-12-17 14:08:07.647833

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM


# revision identifiers, used by Alembic.
revision = '7c94b0590246'
down_revision = '7e12f25f42a3'
branch_labels = None
depends_on = None


album_type_enum = ENUM('album', 'single', 'compilation', name='album_type_enum', create_type=False)


def upgrade():
    album_type_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('spotify_id', sa.String(length=128), nullable=True),
    sa.Column('image_url_640px', sa.String(length=512), nullable=True),
    sa.Column('image_url_320px', sa.String(length=512), nullable=True),
    sa.Column('image_url_160px', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spotify_id')
    )
    op.create_table('tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('track_order', sa.Integer(), nullable=True),
    sa.Column('isrc', sa.String(length=30), nullable=True),
    sa.Column('ean', sa.String(length=30), nullable=True),
    sa.Column('upc', sa.String(length=30), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('explicit', sa.Boolean(), nullable=True),
    sa.Column('spotify_id', sa.String(length=128), nullable=True),
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ean'),
    sa.UniqueConstraint('isrc'),
    sa.UniqueConstraint('spotify_id'),
    sa.UniqueConstraint('upc')
    )
    op.create_table('track_artist',
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('track_id', 'artist_id')
    )
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration_ms', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('explicit', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('label', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('isrc', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('upc', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('ean', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('album_type', sa.Enum('album', 'single', 'compilation', name='album_type_enum'), nullable=False))
        batch_op.add_column(sa.Column('spotify_id', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('image_url_640px', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('image_url_300px', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('image_url_64px', sa.String(length=512), nullable=True))
        batch_op.create_unique_constraint(None, ['upc'])
        batch_op.create_unique_constraint(None, ['spotify_id'])
        batch_op.create_unique_constraint(None, ['ean'])
        batch_op.create_unique_constraint(None, ['isrc'])
        batch_op.drop_column('release_date')
        batch_op.drop_column('artist')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artist', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('release_date', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('image_url_64px')
        batch_op.drop_column('image_url_300px')
        batch_op.drop_column('image_url_640px')
        batch_op.drop_column('spotify_id')
        batch_op.drop_column('album_type')
        batch_op.drop_column('ean')
        batch_op.drop_column('upc')
        batch_op.drop_column('isrc')
        batch_op.drop_column('label')
        batch_op.drop_column('explicit')
        batch_op.drop_column('duration_ms')

    op.drop_table('track_artist')
    op.drop_table('tracks')
    op.drop_table('artists')
    # ### end Alembic commands ###

    album_type_enum.drop(op.get_bind(), checkfirst=True)
