"""remove not null constrant from reviews.is_private

Revision ID: 98c42912bdaa
Revises: 45530d49033d
Create Date: 2025-01-28 19:40:22.823143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98c42912bdaa'
down_revision = '45530d49033d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('is_private',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('is_private',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
