"""remove unique constraint from spotify id columns in revews and catalog_items tables

Revision ID: c44b2c153d03
Revises: 09aef735abb2
Create Date: 2025-01-23 14:48:23.822892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c44b2c153d03'
down_revision = '09aef735abb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalog_items', schema=None) as batch_op:
        batch_op.drop_constraint('catalog_items_spotify_artist_id_key', type_='unique')
        batch_op.drop_constraint('catalog_items_spotify_id_key', type_='unique')
        batch_op.drop_column('private')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint('reviews_spotify_artist_id_key', type_='unique')
        batch_op.drop_constraint('reviews_spotify_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_unique_constraint('reviews_spotify_id_key', ['spotify_id'])
        batch_op.create_unique_constraint('reviews_spotify_artist_id_key', ['spotify_artist_id'])

    with op.batch_alter_table('catalog_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('private', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('catalog_items_spotify_id_key', ['spotify_id'])
        batch_op.create_unique_constraint('catalog_items_spotify_artist_id_key', ['spotify_artist_id'])

    # ### end Alembic commands ###
