"""add display_name and profile_pic_url columns to users table

Revision ID: fbab0c91ebfc
Revises: f99f282090ab
Create Date: 2025-01-27 17:55:09.713106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbab0c91ebfc'
down_revision = 'f99f282090ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('profile_pic_url', sa.String(length=256), nullable=True))
        batch_op.create_unique_constraint(None, ['display_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('profile_pic_url')
        batch_op.drop_column('display_name')

    # ### end Alembic commands ###
